# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf58db2e356b043f8e540e1e24616262c1f45802d412f01e181dd3bb7b4c302d58f3c1116bd8576367580dc462f5962e08f80f547b2da79bbadcb33e53087641

test:
  secret_key_base: 7064770d07e0ac495842453aca252709d6fa809c84c401d69a8df42f4864b3283a823cbb87434ad6a19b9f52c40113a05edc19fee71782bb8b29663cb5e9e641

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
